# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 12:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uyeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aktif', models.BooleanField(default=1)),
                ('MailGonderebilir', models.BooleanField(default=0, verbose_name='Mail G\xf6nderebilir')),
                ('YorumYapabilir', models.BooleanField(default=1, verbose_name='Yorum Yapabilir')),
                ('KayitLimiti', models.IntegerField(default=1000, verbose_name='Kay\u0131t Limiti')),
                ('Ad', models.CharField(max_length=100, verbose_name='Ad\u0131')),
                ('SoyAd', models.CharField(max_length=100, verbose_name='Soyad\u0131')),
                ('Domain', models.CharField(default='http://www.', max_length=250, unique=True, verbose_name='Domain')),
                ('Parola', models.CharField(default='EGBQBRZ1', max_length=15, verbose_name='Parola')),
                ('Maili', models.EmailField(max_length=250, unique=True, verbose_name='Mail Adresi')),
                ('Logo', models.FileField(blank=True, help_text='G\xf6rsel y\xfcksekli\u011fi 200px, geni\u015fli\u011fi 200px olarak g\xf6sterilecek.', max_length=250, null=True, upload_to='profilfoto/', verbose_name='Logo')),
                ('KayitTarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Kay\u0131t Tarihi')),
                ('BitisTarihi', models.DateField(default=datetime.datetime(2016, 5, 24, 12, 45, 1, 793140), verbose_name='Biti\u015f Tarihi')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\xdcye',
                'verbose_name_plural': '\xdcyeler',
            },
        ),
    ]
