# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uyeler', '0006_auto_20160509_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uyeler',
            name='BitisTarihi',
            field=models.DateField(default=datetime.datetime(2016, 5, 24, 13, 46, 6, 902050), verbose_name='Biti\u015f Tarihi'),
        ),
        migrations.AlterField(
            model_name='uyeler',
            name='Parola',
            field=models.CharField(default='3ZIEK5PW', max_length=15, verbose_name='Parola'),
        ),
    ]
